In [3]:
import pandas as pd
df = pd.read_csv("imoveis_aquisicoes_brasil.csv.gz")
df

,logradouro,tipo_logradouro,bairro,cidade,cep,tipo,valor,data_aquisicao
0,Quinta do Sol,Rua,Alto da Pedreira,Belo Horizonte,30840439,Terreno,1192500.0,2015-10-10
1,Antonio Loureiro,Rua,Alto da Pedreira,Belo Horizonte,30026486,Casa,1127500.0,2016-12-02
2,Canario Branco Central,Rua,Alto da Pedreira,Belo Horizonte,31093672,Kitnet,247000.0,2017-05-11
3,das Palmeiras,Avenida,Alto da Pedreira,Belo Horizonte,30166283,Cobertura,2095000.0,2017-05-17
4,Antonio Loureiro,Rua,Alto da Pedreira,Belo Horizonte,30031522,Terreno,1392500.0,2019-04-06
...,...,...,...,...,...,...,...,...
1495,Veredas do Lago,Rua,Vila Primavera,Sao Paulo,4607074,Casa,1132500.0,2024-06-22
1496,dos Ipes,Estrada,Vila Primavera,Sao Paulo,5744464,Casa,1700000.0,2024-12-14
1497,Benedito Campos,Rua,Vila Primavera,Sao Paulo,5563640,Casa,757500.0,2025-04-19
1498,Joao Marin,Rua,Vila Primavera,Sao Paulo,5177091,Sobrado,2205000.0,2025-07-04
1499,Monte Claro,Travessa,Vila Primavera,Sao Paulo,5614926,Kitnet,279000.0,2025-10-22

a) Quantas colunas o dataset possui?

In [4]:
df.columns

Index(['logradouro', 'tipo_logradouro', 'bairro', 'cidade', 'cep', 'tipo',
       'valor', 'data_aquisicao'],
      dtype='str')

b)Quantas colunas numéricas o dataset possui?

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   logradouro       1500 non-null   str
 1   tipo_logradouro  1500 non-null   str
 2   bairro           1500 non-null   str
 3   cidade           1500 non-null   str
 4   cep              1500 non-null   int64
 5   tipo             1500 non-null   str
 6   valor            1500 non-null   float64
 7   data_aquisicao   1500 non-null   str
dtypes: float64(1), int64(1), str(6)
memory usage: 93.9 KB

c)Quantas linhas tem o dataset?

In [7]:
len(df)

1500

d) Escreva o endereço completo do imóvel com o maior valor

In [ ]:
df.sort_values("valor")

,logradouro,tipo_logradouro,bairro,cidade,cep,tipo,valor,data_aquisicao
903,Joao Marin,Estrada,Parque das Aroeiras,Ribeirao Preto,14107955,Kitnet,87000.0,2024-06-11
523,das Cerejeiras,Rua,Vila Lagoa Serena,Fortaleza,60289143,Kitnet,87000.0,2021-01-10
928,dos Ipes,Travessa,Vila Santa Clara Alta,Ribeirao Preto,14041656,Kitnet,90500.0,2017-02-21
135,Paineiras,Estrada,Vila Ouro Preto Nova,Belo Horizonte,30692918,Kitnet,91000.0,2014-10-21
569,Veredas do Lago Central,Rua,Residencial Anhanguera Sul,Goiania,74762431,Kitnet,92000.0,2018-07-10
...,...,...,...,...,...,...,...,...
189,Clara Nogueira,Alameda,Jardim Cambui Novo,Campinas,13081572,Galpao,4140000.0,2022-08-09
606,Olivia Monteiro,Praca,Campo Oceano Verde,Niteroi,24102964,Galpao,4635000.0,2024-10-06
1326,Morro Azul,Rua,Jardim Laranjeiras,Sao Paulo,3976099,Galpao,5470000.0,2021-08-28
1264,Campo Sereno,Rua,Residencial Aquarius Sul,Sao Jose dos Campos,12263657,Galpao,6220000.0,2024-01-15
328,Joao Marin,Avenida,Parque Barigui Novo,Curitiba,82034457,Galpao,6570000.0,2019-10-17

e)Escreva o endereço completo do imóvel com o menor valor?

In [11]:
df.sort_values("valor",ascending=False)

,logradouro,tipo_logradouro,bairro,cidade,cep,tipo,valor,data_aquisicao
328,Joao Marin,Avenida,Parque Barigui Novo,Curitiba,82034457,Galpao,6570000.0,2019-10-17
1264,Campo Sereno,Rua,Residencial Aquarius Sul,Sao Jose dos Campos,12263657,Galpao,6220000.0,2024-01-15
1326,Morro Azul,Rua,Jardim Laranjeiras,Sao Paulo,3976099,Galpao,5470000.0,2021-08-28
606,Olivia Monteiro,Praca,Campo Oceano Verde,Niteroi,24102964,Galpao,4635000.0,2024-10-06
189,Clara Nogueira,Alameda,Jardim Cambui Novo,Campinas,13081572,Galpao,4140000.0,2022-08-09
...,...,...,...,...,...,...,...,...
569,Veredas do Lago Central,Rua,Residencial Anhanguera Sul,Goiania,74762431,Kitnet,92000.0,2018-07-10
135,Paineiras,Estrada,Vila Ouro Preto Nova,Belo Horizonte,30692918,Kitnet,91000.0,2014-10-21
928,dos Ipes,Travessa,Vila Santa Clara Alta,Ribeirao Preto,14041656,Kitnet,90500.0,2017-02-21
903,Joao Marin,Estrada,Parque das Aroeiras,Ribeirao Preto,14107955,Kitnet,87000.0,2024-06-11
523,das Cerejeiras,Rua,Vila Lagoa Serena,Fortaleza,60289143,Kitnet,87000.0,2021-01-10

f)Calcule a soma dos valores de todos os imóveis da tabela

In [15]:
df["valor"].sum()

np.float64(1316455000.0)


g)Calcule a média do valor dos imóveis da tabela?

In [16]:
df["valor"].mean()

np.float64(877636.6666666666)

h)Calcule a mediana do valor dos imóveis da tabela?

In [17]:
df["valor"].median()

np.float64(712500.0)

j)Calcule o desvio padrão do valor dos imóveis da tabela?

In [18]:
df["valor"].std()

np.float64(646676.0007057745)