In [2]:
import pandas as pd
df = pd.read_csv("imoveis_aquisicoes_brasil.csv.gz")
df

,logradouro,tipo_logradouro,bairro,cidade,cep,tipo,valor,data_aquisicao
0,Quinta do Sol,Rua,Alto da Pedreira,Belo Horizonte,30840439,Terreno,1192500.0,2015-10-10
1,Antonio Loureiro,Rua,Alto da Pedreira,Belo Horizonte,30026486,Casa,1127500.0,2016-12-02
2,Canario Branco Central,Rua,Alto da Pedreira,Belo Horizonte,31093672,Kitnet,247000.0,2017-05-11
3,das Palmeiras,Avenida,Alto da Pedreira,Belo Horizonte,30166283,Cobertura,2095000.0,2017-05-17
4,Antonio Loureiro,Rua,Alto da Pedreira,Belo Horizonte,30031522,Terreno,1392500.0,2019-04-06
...,...,...,...,...,...,...,...,...
1495,Veredas do Lago,Rua,Vila Primavera,Sao Paulo,4607074,Casa,1132500.0,2024-06-22
1496,dos Ipes,Estrada,Vila Primavera,Sao Paulo,5744464,Casa,1700000.0,2024-12-14
1497,Benedito Campos,Rua,Vila Primavera,Sao Paulo,5563640,Casa,757500.0,2025-04-19
1498,Joao Marin,Rua,Vila Primavera,Sao Paulo,5177091,Sobrado,2205000.0,2025-07-04
1499,Monte Claro,Travessa,Vila Primavera,Sao Paulo,5614926,Kitnet,279000.0,2025-10-22

a) Quantas colunas o dataset possui?

In [3]:
df.columns

Index(['logradouro', 'tipo_logradouro', 'bairro', 'cidade', 'cep', 'tipo',
       'valor', 'data_aquisicao'],
      dtype='str')

b)Quantas colunas numéricas o dataset possui?

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   logradouro       1500 non-null   str
 1   tipo_logradouro  1500 non-null   str
 2   bairro           1500 non-null   str
 3   cidade           1500 non-null   str
 4   cep              1500 non-null   int64
 5   tipo             1500 non-null   str
 6   valor            1500 non-null   float64
 7   data_aquisicao   1500 non-null   str
dtypes: float64(1), int64(1), str(6)
memory usage: 93.9 KB

c)Quantas linhas tem o dataset?

In [5]:
len(df)

1500

d) Escreva o endereço completo do imóvel com o maior valor

In [6]:
df.sort_values("valor")

,logradouro,tipo_logradouro,bairro,cidade,cep,tipo,valor,data_aquisicao
903,Joao Marin,Estrada,Parque das Aroeiras,Ribeirao Preto,14107955,Kitnet,87000.0,2024-06-11
523,das Cerejeiras,Rua,Vila Lagoa Serena,Fortaleza,60289143,Kitnet,87000.0,2021-01-10
928,dos Ipes,Travessa,Vila Santa Clara Alta,Ribeirao Preto,14041656,Kitnet,90500.0,2017-02-21
135,Paineiras,Estrada,Vila Ouro Preto Nova,Belo Horizonte,30692918,Kitnet,91000.0,2014-10-21
569,Veredas do Lago Central,Rua,Residencial Anhanguera Sul,Goiania,74762431,Kitnet,92000.0,2018-07-10
...,...,...,...,...,...,...,...,...
189,Clara Nogueira,Alameda,Jardim Cambui Novo,Campinas,13081572,Galpao,4140000.0,2022-08-09
606,Olivia Monteiro,Praca,Campo Oceano Verde,Niteroi,24102964,Galpao,4635000.0,2024-10-06
1326,Morro Azul,Rua,Jardim Laranjeiras,Sao Paulo,3976099,Galpao,5470000.0,2021-08-28
1264,Campo Sereno,Rua,Residencial Aquarius Sul,Sao Jose dos Campos,12263657,Galpao,6220000.0,2024-01-15
328,Joao Marin,Avenida,Parque Barigui Novo,Curitiba,82034457,Galpao,6570000.0,2019-10-17

e)Escreva o endereço completo do imóvel com o menor valor?

In [7]:
df.sort_values("valor",ascending=False)

,logradouro,tipo_logradouro,bairro,cidade,cep,tipo,valor,data_aquisicao
328,Joao Marin,Avenida,Parque Barigui Novo,Curitiba,82034457,Galpao,6570000.0,2019-10-17
1264,Campo Sereno,Rua,Residencial Aquarius Sul,Sao Jose dos Campos,12263657,Galpao,6220000.0,2024-01-15
1326,Morro Azul,Rua,Jardim Laranjeiras,Sao Paulo,3976099,Galpao,5470000.0,2021-08-28
606,Olivia Monteiro,Praca,Campo Oceano Verde,Niteroi,24102964,Galpao,4635000.0,2024-10-06
189,Clara Nogueira,Alameda,Jardim Cambui Novo,Campinas,13081572,Galpao,4140000.0,2022-08-09
...,...,...,...,...,...,...,...,...
569,Veredas do Lago Central,Rua,Residencial Anhanguera Sul,Goiania,74762431,Kitnet,92000.0,2018-07-10
135,Paineiras,Estrada,Vila Ouro Preto Nova,Belo Horizonte,30692918,Kitnet,91000.0,2014-10-21
928,dos Ipes,Travessa,Vila Santa Clara Alta,Ribeirao Preto,14041656,Kitnet,90500.0,2017-02-21
903,Joao Marin,Estrada,Parque das Aroeiras,Ribeirao Preto,14107955,Kitnet,87000.0,2024-06-11
523,das Cerejeiras,Rua,Vila Lagoa Serena,Fortaleza,60289143,Kitnet,87000.0,2021-01-10

f)Calcule a soma dos valores de todos os imóveis da tabela

In [8]:
df["valor"].sum()

np.float64(1316455000.0)


g)Calcule a média do valor dos imóveis da tabela?

In [9]:
df["valor"].mean()

np.float64(877636.6666666666)

h)Calcule a mediana do valor dos imóveis da tabela?

In [10]:
df["valor"].median()

np.float64(712500.0)

j)Calcule o desvio padrão do valor dos imóveis da tabela?

In [11]:
df["valor"].std()

np.float64(646676.0007057745)

k)Exiba apenas os imóveis da cidade "Curitiba"

In [15]:
df[df["cidade"] == "Curitiba"]

,logradouro,tipo_logradouro,bairro,cidade,cep,tipo,valor,data_aquisicao
250,Vale Verde Oeste,Alameda,Alto Capivari,Curitiba,82120169,Kitnet,234000.0,2014-06-24
251,Padre Avelino,Avenida,Alto Capivari,Curitiba,82754280,Casa,1372500.0,2014-08-22
252,das Acacias,Rua,Alto Capivari,Curitiba,80251237,Loja,435000.0,2014-09-02
253,Campo Sereno,Rua,Alto Capivari,Curitiba,82695448,Apartamento,597000.0,2015-06-04
254,Quinta do Sol,Rua,Alto Capivari,Curitiba,80387186,Casa,1130000.0,2015-07-07
...,...,...,...,...,...,...,...,...
360,Serra Bonita,Alameda,Vila Pinheiros,Curitiba,81457564,Sobrado,1490000.0,2018-08-24
361,Canario Branco,Rua,Vila Pinheiros,Curitiba,80817291,Casa,1300000.0,2021-05-20
362,Olivia Monteiro,Rodovia,Vila Pinheiros,Curitiba,80192125,Casa,765000.0,2022-04-04
363,Ribeirao Claro Oeste,Avenida,Vila Pinheiros,Curitiba,81222033,Apartamento,580000.0,2022-05-09
364,Engenheiro Tavares,Rua,Vila Pinheiros,Curitiba,82433117,Kitnet,238000.0,2024-09-02

l)Exiba os imóveis cujo tipo seja "apartamento"

In [18]:
df[df["tipo"]=="Apartamento"]

,logradouro,tipo_logradouro,bairro,cidade,cep,tipo,valor,data_aquisicao
9,Helena Sampaio,Alameda,Alto da Pedreira,Belo Horizonte,31649896,Apartamento,527000.0,2023-06-19
11,Clara Nogueira,Rua,Alto da Pedreira,Belo Horizonte,30333799,Apartamento,1030000.0,2024-10-15
13,Vale Verde,Rua,Alto da Pedreira,Belo Horizonte,31460215,Apartamento,947500.0,2026-03-07
14,Veredas do Lago,Avenida,Jardim Horizonte Azul,Belo Horizonte,30457770,Apartamento,256000.0,2014-09-24
22,Sao Gabriel,Avenida,Jardim Horizonte Azul,Belo Horizonte,31365999,Apartamento,665000.0,2022-03-23
...,...,...,...,...,...,...,...,...
1476,Helena Sampaio Central,Rua,Vila Primavera,Sao Paulo,5173887,Apartamento,551000.0,2014-11-06
1479,Sao Gabriel,Avenida,Vila Primavera,Sao Paulo,1820839,Apartamento,349000.0,2015-12-10
1482,Veredas do Lago,Rua,Vila Primavera,Sao Paulo,5861518,Apartamento,880000.0,2017-03-23
1485,Serra Bonita,Rua,Vila Primavera,Sao Paulo,5813517,Apartamento,842500.0,2018-02-09
1493,Engenheiro Tavares,Rua,Vila Primavera,Sao Paulo,4420706,Apartamento,982500.0,2023-09-26

m)Exiba os imóveis que não sejam do tipo "apartamento" e tenham valor menor ou igual a 600000.

In [20]:
df[(df["tipo"]!="Apartamento") & (df["valor"] <=600000)]

,logradouro,tipo_logradouro,bairro,cidade,cep,tipo,valor,data_aquisicao
2,Canario Branco Central,Rua,Alto da Pedreira,Belo Horizonte,31093672,Kitnet,247000.0,2017-05-11
5,Sao Vicente Sul,Avenida,Alto da Pedreira,Belo Horizonte,31952099,Kitnet,364000.0,2021-01-01
7,Veredas do Lago,Estrada,Alto da Pedreira,Belo Horizonte,31563359,Casa,486000.0,2022-05-03
15,Laranjeiras,Avenida,Jardim Horizonte Azul,Belo Horizonte,31728489,Casa,418000.0,2015-01-27
16,dos Ipes,Avenida,Jardim Horizonte Azul,Belo Horizonte,31849968,Casa,346000.0,2015-02-22
...,...,...,...,...,...,...,...,...
1436,Flor do Campo,Avenida,Vila Horizonte,Sao Paulo,4868406,Sala Comercial,540000.0,2018-02-09
1481,Ribeirao Claro Norte,Rua,Vila Primavera,Sao Paulo,4841355,Casa,447000.0,2016-05-12
1486,Porto das Flores,Avenida,Vila Primavera,Sao Paulo,5813031,Kitnet,222000.0,2018-10-12
1489,Capitao Noronha,Rua,Vila Primavera,Sao Paulo,2712517,Kitnet,245000.0,2022-04-07
1499,Monte Claro,Travessa,Vila Primavera,Sao Paulo,5614926,Kitnet,279000.0,2025-10-22

n)Exiba os imóveis da cidade "Curitiba" cujo bairro não seja "Residencial Tingui".

In [21]:
df[(df["cidade"] =="Curitiba") & (df["bairro"]!="Residencial Tingui")]

,logradouro,tipo_logradouro,bairro,cidade,cep,tipo,valor,data_aquisicao
250,Vale Verde Oeste,Alameda,Alto Capivari,Curitiba,82120169,Kitnet,234000.0,2014-06-24
251,Padre Avelino,Avenida,Alto Capivari,Curitiba,82754280,Casa,1372500.0,2014-08-22
252,das Acacias,Rua,Alto Capivari,Curitiba,80251237,Loja,435000.0,2014-09-02
253,Campo Sereno,Rua,Alto Capivari,Curitiba,82695448,Apartamento,597000.0,2015-06-04
254,Quinta do Sol,Rua,Alto Capivari,Curitiba,80387186,Casa,1130000.0,2015-07-07
...,...,...,...,...,...,...,...,...
360,Serra Bonita,Alameda,Vila Pinheiros,Curitiba,81457564,Sobrado,1490000.0,2018-08-24
361,Canario Branco,Rua,Vila Pinheiros,Curitiba,80817291,Casa,1300000.0,2021-05-20
362,Olivia Monteiro,Rodovia,Vila Pinheiros,Curitiba,80192125,Casa,765000.0,2022-04-04
363,Ribeirao Claro Oeste,Avenida,Vila Pinheiros,Curitiba,81222033,Apartamento,580000.0,2022-05-09
364,Engenheiro Tavares,Rua,Vila Pinheiros,Curitiba,82433117,Kitnet,238000.0,2024-09-02

o) Exiba os imóveis cujo valor seja maior que a média geral e cuja data de aquisição seja anterior a 2021-01-01.

In [24]:
df[(df["valor"]> df["valor"].mean()) & (df["data_aquisicao"] < "2021-01-01")]

,logradouro,tipo_logradouro,bairro,cidade,cep,tipo,valor,data_aquisicao
0,Quinta do Sol,Rua,Alto da Pedreira,Belo Horizonte,30840439,Terreno,1192500.0,2015-10-10
1,Antonio Loureiro,Rua,Alto da Pedreira,Belo Horizonte,30026486,Casa,1127500.0,2016-12-02
3,das Palmeiras,Avenida,Alto da Pedreira,Belo Horizonte,30166283,Cobertura,2095000.0,2017-05-17
4,Antonio Loureiro,Rua,Alto da Pedreira,Belo Horizonte,30031522,Terreno,1392500.0,2019-04-06
17,Antonio Loureiro,Rua,Jardim Horizonte Azul,Belo Horizonte,31840545,Galpao,2490000.0,2015-05-05
...,...,...,...,...,...,...,...,...
1480,Flor do Campo Central,Rua,Vila Primavera,Sao Paulo,2889729,Casa,1082500.0,2016-02-08
1482,Veredas do Lago,Rua,Vila Primavera,Sao Paulo,5861518,Apartamento,880000.0,2017-03-23
1484,Helena Sampaio Oeste,Avenida,Vila Primavera,Sao Paulo,2557295,Casa,1345000.0,2017-07-02
1487,das Mangueiras,Largo,Vila Primavera,Sao Paulo,4122666,Sobrado,1407500.0,2020-10-01
1488,Raul Peixoto Norte,Rua,Vila Primavera,Sao Paulo,4063339,Casa,1127500.0,2020-10-17

p)Exiba os imóveis cujo tipo de logradouro seja "Avenida" e cujo valor esteja entre 400000 e 1000000.

In [28]:
df[(df["tipo_logradouro"]=="Avenida") & (df["valor"] >= 400000) & (df["valor"] <=1000000)]

,logradouro,tipo_logradouro,bairro,cidade,cep,tipo,valor,data_aquisicao
15,Laranjeiras,Avenida,Jardim Horizonte Azul,Belo Horizonte,31728489,Casa,418000.0,2015-01-27
20,Alto do Cedro,Avenida,Jardim Horizonte Azul,Belo Horizonte,30158676,Sobrado,670000.0,2021-05-03
22,Sao Gabriel,Avenida,Jardim Horizonte Azul,Belo Horizonte,31365999,Apartamento,665000.0,2022-03-23
23,Horizonte Azul,Avenida,Jardim Horizonte Azul,Belo Horizonte,30327391,Apartamento,466000.0,2023-04-13
24,Padre Avelino,Avenida,Jardim Horizonte Azul,Belo Horizonte,30898169,Apartamento,558000.0,2023-10-09
...,...,...,...,...,...,...,...,...
1393,Porto das Flores,Avenida,Parque das Fontes,Sao Paulo,1150951,Apartamento,950000.0,2024-10-08
1431,Engenheiro Tavares,Avenida,Vila Campos Verdes,Sao Paulo,1021408,Apartamento,552000.0,2025-03-27
1436,Flor do Campo,Avenida,Vila Horizonte,Sao Paulo,4868406,Sala Comercial,540000.0,2018-02-09
1440,Serra Bonita,Avenida,Vila Horizonte,Sao Paulo,4646144,Casa,982500.0,2021-08-17
1483,Sao Vicente,Avenida,Vila Primavera,Sao Paulo,1249744,Terreno,692500.0,2017-05-01

q)Exiba o apartamento mais caro da cidade "Belo Horizonte"

In [29]:
df[(df["tipo"]=="Apartamento") & (df["cidade"]=="Belo Horizonte")].max()

logradouro               dos Jacarandas
tipo_logradouro                Travessa
bairro             Vila Ouro Preto Nova
cidade                   Belo Horizonte
cep                            31994522
tipo                        Apartamento
valor                         1077500.0
data_aquisicao               2026-04-01
dtype: object

r) Exiba o valor médio das casas no bairro "Parque das Mangueiras" da cidade "Belo Horizonte"

In [32]:
df[(df["bairro"]=="Parque das Mangueiras") & (df["cidade"]=="Belo Horizonte")]["valor"].mean()

np.float64(728952.380952381)

s)Calcule a diferença entre o imóvel mais caro e o imóvel mais barato da cidade "Campinas"

In [34]:
df[(df["cidade"]=="Campinas")]["valor"].max() - df[(df["cidade"]=="Campinas")]["valor"].min()

np.float64(3977000.0)

t)Calcule o valor total dos imóveis cadastrados no bairro "Residencial Anhumas"

In [35]:
df[(df["bairro"]=="Residencial Anhumas")]["valor"].sum()

np.float64(11597000.0)

u)Exiba os imóveis do tipo "Apartamento" no bairro "Residencial Anhumas" cujo valor esteja acima da média geral dos apartamentos desse mesmo bairro

In [38]:
media=df[(df["tipo"]== "Apartamento") & (df["bairro"] == "Residencial Anhumas")]["valor"].mean()
df[(df["tipo"]=="Apartamento") & (df["bairro"]=="Residencial Anhumas") & (df["valor"]>media)]

,logradouro,tipo_logradouro,bairro,cidade,cep,tipo,valor,data_aquisicao
218,das Orquideas,Alameda,Residencial Anhumas,Campinas,13048881,Apartamento,650000.0,2018-07-25
222,Maria Valenca,Rua,Residencial Anhumas,Campinas,13051951,Apartamento,832500.0,2021-10-16
223,Sao Gabriel,Avenida,Residencial Anhumas,Campinas,13006533,Apartamento,687500.0,2022-01-16
226,Helena Sampaio,Rua,Residencial Anhumas,Campinas,13053716,Apartamento,885000.0,2025-12-05