In [10]:
print("ola,mundo")

ola,mundo

https://cognitrilha.com.br/datasets/imoveis.csv.gz

Exiba as primeiras e últimas linhas do DataFrame (head e tail)

Verifique valores ausentes (NaN) em todas as colunas

Ordene o DataFrame pela data em ordem crescente

Calcule a soma dos valores de todos os imoveis da tabela

Calcule a média do valor de imoveis da tabela

Exiba apenas as colunas logradouro e valor dos imóveis

Exiba apenas os imóveis da cidade "Lake Michael"

Exiba os imóveis cujo tipo seja "apartamento".

Exiba apenas as colunas logradouro e valor dos imóveis com valor maior que 500000.

Exiba todas as colunas dos imóveis do bairro "Potterbury".

Exiba apenas as colunas logradouro, valor e tipo dos imóveis com valor entre 300000 e 600000.

Exiba todas as colunas dos imóveis com data de aquisição posterior a 2020-01-01.

In [11]:
import pandas as pd
df=pd.read_csv("https://cognitrilha.com.br/datasets/imoveis.csv.gz")
df

,id,logradouro,tipo_logradouro,bairro,cidade,cep,tipo,valor,data_aquisicao
0,2,Price Prairie,Travessa,Colonton,North Garyville,93354,casa em condominio,260069.89,2021-11-30
1,3,Taylor Ranch,Avenida,West Jennashire,Katherinefurt,51116,apartamento,815969.92,2020-04-24
2,4,Stacey Isle,Avenida,Reneeberg,Bentleymouth,1631,terreno,352507.35,2014-11-03
3,5,Taylor Causeway,Rua,Burkeview,Port Cynthia,9893,casa em condominio,929368.49,2023-05-10
4,6,Preston Terrace,Rua,North Lindseyview,Lake Michael,99549,terreno,946804.25,2023-12-13
...,...,...,...,...,...,...,...,...,...
995,997,Johnson Mills,Avenida,Lake Elizabethshire,Port Christopherfort,89590,apartamento,901689.96,2022-10-21
996,998,Gary Groves,Avenida,Ramirezhaven,North Brandon,65952,terreno,830146.70,2016-01-22
997,999,Amber Avenue,Avenida,Russellton,Roseland,68912,casa em condominio,284884.65,2016-05-24
998,1000,Wheeler Falls,Avenida,Matthewbury,New Brandonborough,18235,terreno,875932.19,2023-01-23
999,1001,Nicole Common,Travessa,Lake Danielle,Judymouth,85184,casa em condominio,488423.52,2017-07-29

In [12]:
df.tail(3)

,id,logradouro,tipo_logradouro,bairro,cidade,cep,tipo,valor,data_aquisicao
997,999,Amber Avenue,Avenida,Russellton,Roseland,68912,casa em condominio,284884.65,2016-05-24
998,1000,Wheeler Falls,Avenida,Matthewbury,New Brandonborough,18235,terreno,875932.19,2023-01-23
999,1001,Nicole Common,Travessa,Lake Danielle,Judymouth,85184,casa em condominio,488423.52,2017-07-29

In [13]:
df.isna().sum()

id                 0
logradouro         0
tipo_logradouro    0
bairro             0
cidade             0
cep                0
tipo               0
valor              0
data_aquisicao     0
dtype: int64

In [14]:
df.sort_values("data_aquisicao")

,id,logradouro,tipo_logradouro,bairro,cidade,cep,tipo,valor,data_aquisicao
572,574,Cynthia Port,Alameda,Garciastad,Smithville,726,terreno,95377.25,2014-02-09
901,903,Angela Pass,Travessa,Jenniferport,Lake Jessicaside,38018,casa em condominio,313201.60,2014-02-13
68,70,Hector Burg,Avenida,Jonesport,East Kelseyville,2428,casa,422127.01,2014-02-16
281,283,Stacey Island,Rua,South Joshua,New Alvin,6873,casa,288794.84,2014-02-21
932,934,Matthew Ways,Alameda,South Jeffrey,Lake Jessicamouth,9229,terreno,729441.59,2014-02-24
...,...,...,...,...,...,...,...,...,...
534,536,Miguel Station,Rua,West Darrell,Edwinburgh,88593,casa,609797.06,2024-01-15
155,157,Burnett Orchard,Rua,Rogerfort,Hunterport,18318,casa em condominio,971364.78,2024-01-16
930,932,Margaret Vista,Avenida,Davidfort,Scottland,67326,terreno,67117.78,2024-01-18
882,884,Smith Square,Avenida,Barretthaven,East Steven,4809,casa em condominio,818648.79,2024-01-22
914,916,Tracey Pass,Alameda,Lake Danielle,North Charleneborough,50600,terreno,724963.97,2024-02-06

In [17]:
df["valor"].sum()

np.float64(515212337.45000005)

In [20]:
df["valor"].sum()/len(df["valor"])

np.float64(515212.33745000005)

In [21]:
df["valor"].mean()

np.float64(515212.33745000005)

In [26]:
df[["logradouro","valor"]]

          logradouro      valor
0      Price Prairie  260069.89
1       Taylor Ranch  815969.92
2        Stacey Isle  352507.35
3    Taylor Causeway  929368.49
4    Preston Terrace  946804.25
..               ...        ...
995    Johnson Mills  901689.96
996      Gary Groves  830146.70
997     Amber Avenue  284884.65
998    Wheeler Falls  875932.19
999    Nicole Common  488423.52

[1000 rows x 2 columns]

In [27]:
df[df["cidade"] =="Lake Michael"]

,id,logradouro,tipo_logradouro,bairro,cidade,cep,tipo,valor,data_aquisicao
4,6,Preston Terrace,Rua,North Lindseyview,Lake Michael,99549,terreno,946804.25,2023-12-13
162,164,Lori Summit,Travessa,Kristaside,Lake Michael,24473,casa,498926.13,2019-02-27
206,208,Cox Stream,Avenida,Port Jeffrey,Lake Michael,39468,casa em condominio,678854.07,2016-12-14
331,333,Joshua Green,Avenida,South Elijah,Lake Michael,13884,casa,115533.24,2017-12-24

In [29]:
df[df["tipo"]=="apartamento"]

,id,logradouro,tipo_logradouro,bairro,cidade,cep,tipo,valor,data_aquisicao
1,3,Taylor Ranch,Avenida,West Jennashire,Katherinefurt,51116,apartamento,815969.92,2020-04-24
7,9,Stone Lane,Travessa,Lake Alexandra,Potterburgh,25991,apartamento,64900.40,2015-05-11
8,10,White Ridge,Travessa,New Andreafurt,Stewartton,42933,apartamento,671553.65,2016-02-16
14,16,Patton Circle,Avenida,New Philipstad,Simonshire,72102,apartamento,473965.52,2017-11-30
19,21,Floyd Haven,Avenida,East Dennisside,Port Kathryn,59133,apartamento,489728.92,2014-11-18
...,...,...,...,...,...,...,...,...,...
972,974,Gonzalez Union,Travessa,West Garrettborough,Port Lindatown,86936,apartamento,948278.89,2014-04-16
973,975,Christina Roads,Rua,Rodrigueztown,Kaylaville,99038,apartamento,100660.81,2017-01-12
978,980,Larry Spurs,Travessa,New Sheilaside,New Ritashire,69094,apartamento,239280.94,2019-05-06
992,994,Clark Extension,Rua,East Calvin,Lake Colin,53306,apartamento,978501.02,2023-10-30
995,997,Johnson Mills,Avenida,Lake Elizabethshire,Port Christopherfort,89590,apartamento,901689.96,2022-10-21

In [31]:
df[["logradouro","valor"]][df["valor"]>= 500000]

          logradouro      valor
1       Taylor Ranch  815969.92
3    Taylor Causeway  929368.49
4    Preston Terrace  946804.25
5    Barbara Springs  702083.39
6      Richard Light  684707.40
..               ...        ...
987  Gabriel Passage  580474.97
992  Clark Extension  978501.02
995    Johnson Mills  901689.96
996      Gary Groves  830146.70
998    Wheeler Falls  875932.19

[493 rows x 2 columns]

In [32]:
df[df["bairro"]=="Potterbury"]

,id,logradouro,tipo_logradouro,bairro,cidade,cep,tipo,valor,data_aquisicao
5,7,Barbara Springs,Alameda,Potterbury,Hayleyview,88290,casa em condominio,702083.39,2021-12-22

In [36]:
df[["logradouro","valor","tipo"]][(df["valor"] >=300000) & (df["valor"] <=600000)]

         logradouro      valor                tipo
2       Stacey Isle  352507.35             terreno
13   Scott Parkways  386662.67  casa em condominio
14    Patton Circle  473965.52         apartamento
15   Thompson Ranch  315406.49                casa
19      Floyd Haven  489728.92         apartamento
..              ...        ...                 ...
989     Emily Shore  467146.94  casa em condominio
990   Natasha Shoal  486348.40  casa em condominio
993   Calderon Isle  377922.07                casa
994     Andre Falls  476504.58                casa
999   Nicole Common  488423.52  casa em condominio

[339 rows x 3 columns]

In [38]:
df[df["data_aquisicao"]>="2020-01-01"]

,id,logradouro,tipo_logradouro,bairro,cidade,cep,tipo,valor,data_aquisicao
0,2,Price Prairie,Travessa,Colonton,North Garyville,93354,casa em condominio,260069.89,2021-11-30
1,3,Taylor Ranch,Avenida,West Jennashire,Katherinefurt,51116,apartamento,815969.92,2020-04-24
3,5,Taylor Causeway,Rua,Burkeview,Port Cynthia,9893,casa em condominio,929368.49,2023-05-10
4,6,Preston Terrace,Rua,North Lindseyview,Lake Michael,99549,terreno,946804.25,2023-12-13
5,7,Barbara Springs,Alameda,Potterbury,Hayleyview,88290,casa em condominio,702083.39,2021-12-22
...,...,...,...,...,...,...,...,...,...
987,989,Gabriel Passage,Avenida,East Carl,Port Courtneybury,92826,casa,580474.97,2020-09-04
992,994,Clark Extension,Rua,East Calvin,Lake Colin,53306,apartamento,978501.02,2023-10-30
994,996,Andre Falls,Rua,East Donna,Hesston,34347,casa,476504.58,2023-09-18
995,997,Johnson Mills,Avenida,Lake Elizabethshire,Port Christopherfort,89590,apartamento,901689.96,2022-10-21
998,1000,Wheeler Falls,Avenida,Matthewbury,New Brandonborough,18235,terreno,875932.19,2023-01-23