# Chegou a hora de praticar!
# Crie o DataFrame abaixo com os dados de 5 alunos e resolva as tarefas propostas.
# Tente antes de ver a solução nas próximas seções! 📝 Enunciado Crie um DataFrame chamado df_alunos com as seguintes colunas:
# • nome: nome do aluno (string) • idade: idade em anos (inteiro) • nota: nota de 0 a 100 (float) 
# Inclua 5 alunos com dados variados. Depois,
# resolva: 1. 
# Filtre e exiba os alunos com nota acima de 80 2. Calcule e exiba a média das notas 3. Exiba a nota máxima e a nota mínima

In [3]:
import pandas as pd
alunos={
    "nome":["Ana","Bruno","Carla","Diego","Eva"],
    "idade":[20,18,25,24,27],
    "nota":[89,58.9,96,79.9,81]
}
df_alunos=pd.DataFrame(alunos)
df_alunos

    nome  idade  nota
0    Ana     20  89.0
1  Bruno     18  58.9
2  Carla     25  96.0
3  Diego     24  79.9
4    Eva     27  81.0

In [4]:
df_alunos[df_alunos["nota"] > 80]

    nome  idade  nota
0    Ana     20  89.0
2  Carla     25  96.0
4    Eva     27  81.0

In [5]:
df_alunos["nota"].mean()

np.float64(80.96000000000001)